vim.api.nvim_set_hl(0, "@keyword", { fg = "#519377" })
vim.api.nvim_set_hl(0, "@constructor", { fg = "#519377" })
vim.api.nvim_set_hl(0, "@go_import_string", { fg = "#82a66b", underline = true })
vim.api.nvim_set_hl(0, "@function", { fg = "#82a66b" })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = "#82a66b" })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = "#82a66b" })
vim.api.nvim_set_hl(0, "@string", { fg = "#b88176" })
vim.api.nvim_set_hl(0, "@attr_classname", { fg = "#b88176", underdotted = true })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = "#b88176" })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#b88176", bold = false })
vim.api.nvim_set_hl(0, "@variable", { fg = "#b6936c" })
vim.api.nvim_set_hl(0, "@property", { fg = "#b6936c" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#666666" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = "#666666" })
vim.api.nvim_set_hl(0, "@module", { fg = "#61a995" })
vim.api.nvim_set_hl(0, "@constant", { fg = "#61a995" })
vim.api.nvim_set_hl(0, "@type", { fg = "#61a995" })
vim.api.nvim_set_hl(0, "@boolean", { fg = "#61a995" })
vim.api.nvim_set_hl(0, "@number", { fg = "#61a995" })
vim.api.nvim_set_hl(0, "@open_tag", { fg = "#61a995" })
vim.api.nvim_set_hl(0, "@close_tag", { fg = "#61a995" })
vim.api.nvim_set_hl(0, "@tag", { fg = "#61a995" })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = "#6594bc" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#6594bc" })

vim.api.nvim_set_hl(0, "TelescopeNormal", { fg = "#6594bc" })
vim.api.nvim_set_hl(0, "TelescopeMatching", { fg = "#b6936c" })

vim.api.nvim_set_hl(0, "SnacksNormal", { fg = "#6594bc" })
