#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


yabai -m config layout                     bsp            \
                external_bar               off            \
                mouse_follows_focus        off            \
                focus_follows_mouse        off            \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                split_ratio                0.50           \
                auto_balance               off            \
                auto_padding               on             \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                5              \
                bottom_padding             5              \
                left_padding               5              \
                right_padding              5              \
                window_gap                 5



yabai -m rule --add label=float app="^(Navicat Premium Lite|Docker Desktop|Postman)$"    manage=off  grid=4:4:1:1:2:2

yabai -m rule --add app="^(系统设置|System Settings|Raycast|备忘录|微信|WeChat|网易云音乐|NetEaseMusic|Reminders|Safari|钉钉|DingTalk)$" manage=off 

yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
