source ~/oh-my-dotfiles/zsh/env.zsh
source ~/oh-my-dotfiles/zsh/aliases.zsh
source ~/oh-my-dotfiles/zsh/plugins.zsh


eval "$(mise activate zsh)"

ZIM_HOME=~/.zim
# Install missing modules and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
  source /opt/homebrew/opt/zimfw/share/zimfw.zsh init
fi
# Initialize modules.
source ${ZIM_HOME}/init.zsh


# Local 
source ~/.zsh.local


# opencode
export PATH=/Users/vino/.opencode/bin:$PATH
